<?php
    $_isCatalogSearch = ('catalogsearch' == $this->getRequest()->getModuleName());
    
    $_displayType = $this->getDisplayType();
    if ($_isCatalogSearch && $_displayType != Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_DROPDOWN) {
        $_displayType = Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_DEFAULT;
    }
?>

<ol <?php if ($this->getCollapsed() && !$this->getHasSelection() && !$_isCatalogSearch) echo 'class="no-display"'?>  >
<?php if (in_array($_displayType, array(
            Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_DEFAULT,
            Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_WSUBCAT,
        ))): ?>
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="layerednavigation-cat layerednavigation-cat-level-<?php echo max(1, $_item->getLevel())?>">
            <?php if ($_item->getIsSelected()) :?>
                <?php echo $_item->getLabel() ?>
                <?php if ($_item->getCount() > 0):?>
                    (<?php echo $_item->getCount() ?>)
                <?php endif;?>
            <?php else:?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                    <?php echo $_item->getLabel() ?>
                    <?php if ($_item->getCount() > 0):?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif;?>
                </a>
            <?php endif;?>
        </li>
    <?php endforeach ?>
<?php elseif (Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_STATIC2LVL == $_displayType): ?>
    <?php foreach ($this->getItems() as $_item): ?>
        <?php
            $level      = $_item->getLevel();
            $additional = $_item->getIsFolded() ? 'style="display:none"' : '';
            
            $class      = 'layerednavigation-cat layerednavigation-cat-level-' . $level;
            if (1 != $level){
                $class .= ' layerednavigation-cat-parentid-' . $_item->getParentId();
            }
            
            $showIcon = (1 == $level && $_item->getHasChildren());
            $icon = ($_item->getIsChildSelected()) ? 'minus': 'plus';
        ?>
        <li class="<?php echo $class?>" <?php echo $additional?>>
            <?php if ($showIcon): ?><span id="layerednavigation-cat-id-<?php echo $_item->getId()?>" class="layerednavigation-plusminus <?php echo $icon?>"></span><?php endif ?>
            <a <?php if ($_item->getIsSelected()):?>class="layerednavigation-cat-selected"<?php endif?> href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
            <?php if ($_item->getCount() > 0):?>
                <span class="count">(<?php echo $_item->getCount() ?>)</span>
            <?php endif;?>
        </li>
    <?php endforeach ?>
<?php elseif (Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_DROPDOWN == $_displayType): ?>
    <li>
        <select onchange="if (this.value) setLocation(this.value)" class="layerednavigation-select">
            <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
            <option value="">&nbsp;</option>
            <?php foreach ($this->getItems() as $_item): ?>
            <option  value="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                <?php echo $_item->getLabel() ?>
                <?php if ($_item->getCount() > 0):?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif;?>
            </option>
            <?php endforeach ?>
        </select>
    </li>
    <?php elseif (Brander_LayeredNavigation_Model_Catalog_Layer_Filter_Category::DT_ADVANCED == $_displayType): ?>
        <li class="layerednavigation-advanced">
            <ol>
                <?php
                $advancedBlock = Mage::getSingleton('core/layout')->createBlock('layerednavigation/advanced');
                // Prevent caching like it done in Magento code
                echo $advancedBlock->getHtml();
                ?>
            </ol>
        </li>
    <?php elseif (5 == $_displayType): // 0_o 5? ?>
        <?php $subcategories = Mage::getSingleton('core/layout')->createBlock('layerednavigation/subcategories')->getSubcategories(); ?>
        <?php
            /*
             * Adjust Image width Here  
             */
            $imgWidth = "79px;"; 
        ?>
        <?php  if ($subcategories):?>
            <li>
                <ol>
                    <?php foreach ($subcategories as $cat): ?>
                        <li class="layerednavigation-subcategory" style="float: left;text-align: center; width: 50%;">
                            <a href="<?php echo $cat->getUrl(); ?>">
                            <?php if ($cat->getImage()): ?>
                                <img class="layerednavigation-subcategories-img"
                                    title="<?php echo $this->htmlEscape($cat->getName()); ?>" 
                                    alt="<?php echo $this->htmlEscape($cat->getName()); ?>"
                                    src="<?php echo $cat->getImage(); ?>"
                                    width="<?php echo $imgWidth?>"
                                />
                            <?php endif; ?>
                            <?php echo '<br />' . $this->htmlEscape($cat->getName()); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ol>            
            </li>
        <?php endif; ?>
    <?php endif ?>
</ol>