<div class="grid12-4 footer-about">
    <div>
    <?php
/*        <div class="collapsible mobile-collapsible">
        <h6 class="block-title heading">About Us</h6>*/
    ?>
        <div class="block-content">
            <?php $logoObj = $this->getLogo(); ?>
            <a href="<?php echo $this->getUrl('') ?>" class="footer-logo">
                <img src="<?php echo $logoObj->getLogoSrc(); ?>"
                     alt="<?php echo $logoObj->getLogoAlt(); ?>"/>
            </a>
            <?php if ($address = Mage::helper('brander_cmshome')->getSiteCfg('general/store_information/address')): ?>
                <span class="like_h6 block-title heading"><?php echo $this->__('Shop Address:') ?></span>
                <div class="feature first last">
                    <p><?php echo $address ?></p>
                </div>
            <?php endif; ?>

            <?php if ($contacts = trim($this->getChildHtml('footer_blocks.contacts.phones'))): ?>
                <div class="block-content footer-contacts">
                    <?php echo $contacts; ?>
                </div>
            <?php endif; ?>

            <?php if ($hours = Mage::helper('brander_cmshome')->getSiteCfg('general/store_information/hours')): ?>
                <span class="like_h6 block-title heading"><?php echo $this->__('Hours of Operations:') ?></span>
                <div class="feature first last">
                    <p><?php echo $hours ?></p>
                </div>
            <?php endif; ?>

            <?php echo $this->getChildHtml('footer.callbacks'); ?>
        </div>
    </div>
</div>