<div class="grid12-4">
    <div class="footer-block">
        <?php
        /*<div class="collapsible mobile-collapsible">*/
        ?>
        <?php if ($contacts = trim($this->getChildHtml('footer_blocks.contacts.phones'))): ?>
            <?php if (Mage::helper('brander_cmsmenu')->isShowFooterTitle()): ?>
                <span class="like_h6 block-title heading"><?php echo $this->__('Our Contacts:'); ?></span>
            <?php endif; ?>
            <div class="block-content">
                <?php echo $contacts; ?>
                <br/>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <?php echo $this->getChildHtml('footer.callbacks'); ?>
        </div>
        <br/><br/>
    </div>
</div>
