<?php //echo $this->getContentHeading(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contacts') ?></h1>
</div>
<?php echo $this->getContent(); ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="contacts-wrap">
    <div class="contacts-form-holder">
        <form action="<?php echo Mage::getUrl('contacts/index/post/'); ?>" id="contactForm" method="post">
            <div class="fieldset">
                <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <div class="input-box">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="input-text" type="text" />
                        </div>
                    </li>
                    <li class="wide">
                        <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var contactForm = new VarienForm('contactForm', false);
            //]]>
            jQuery("#telephone").mask("+38 (099) 999-99-99");
        </script>
<!--        <div class="contacts-address">-->
<!--            --><?php //if ($address = Mage::helper('brander_shop')->getCfg('general/store_information/address')): ?>
<!--                <div class="feature first last">-->
<!--                    <h6 class="block-title heading">--><?php //echo Mage::helper('contacts')->__('Address'); ?><!--:</h6>-->
<!--                    --><?php //echo $address ?>
<!--                </div>-->
<!--            --><?php //endif; ?>
<!--            --><?php //echo $this->getChildHtml('blocks.contacts'); ?>
<!--            --><?php //if ($hours = Mage::helper('brander_cmshome')->getSiteCfg('general/store_information/hours')): ?>
<!--                <div class="feature work-time">-->
<!--                    <h6 class="block-title heading">--><?php //echo $this->__('Work Time') ?><!--:</h6>-->
<!--                    <span>--><?php //echo $hours ?><!--</span>-->
<!--                </div>-->
<!--            --><?php //endif; ?>
<!--        </div>-->
    </div>
    <div class="contacts-map-holder">
        <?php echo $this->getChildHtml('contacts.map'); ?>
    </div>
</div>
