<?php //echo $this->getContentHeading(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contacts') ?></h1>
</div>
<?php echo $this->getContent(); ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="contacts-wrap">
    <div class="contacts-map-holder">
        <?php echo $this->getChildHtml('contacts.map'); ?>
    </div>
</div>
