<div class="callbacks-popup" id="callbacks" style="display: none">
	<div class="lightbox">
		<div class="lightbox-holder">
			<div class="lightbox-frame">
				<div class="lightbox-content">
					<span class="callbacks_loader" style="display: none"><?php echo $this->__('loading ...')?></span>
					<form action="<?php echo $this->getUrl('customercallbacks/index/callback'); ?>" method="post" name="form_customercallbacks" id="form_customercallbacks" class="webforms-callback">
						<h2><?php echo $this->__("Callback"); ?></h2>
						<p class="callbacks-welcome-message"><?php echo Mage::helper('brander_customercallbacks')->getRequestMessage() ?></p>
						<span class="callbacks_message"></span>
						<div class="field webforms-fields-username clearfix">
							<label for="callbacks_name" class="required"><?php echo $this->__("Your Name"); ?> </label>
							<input type="text" name="name" id="callbacks_name" class="input-text required-entry" value="" />
						</div>
						<div class="field webforms-fields-phonenumber clearfix">
							<label for="callbacks_phone" class="required masked-telephone"><?php echo $this->__("Telephone"); ?> </label>
							<input type="text" name="phone" data-format="+380 dd ddd-dd-dd" id="callbacks_phone" class="input-text required-entry validate-phone-no-empty form-control bfh-phone" value="" />
						</div>

						<?php if(Mage::helper('brander_customercallbacks')->showCommentField()): ?>
							<div class="field webforms-fields-comment clearfix">
								<label for="callbacks_comment"><?php echo $this->__("Comment"); ?> </label>
								<textarea name="comment" id="callbacks_comment" class="input-text" value=""></textarea>
							</div>
						<?php endif; ?>

						<?php $currentPageInfo = '<a href="'.Mage::helper('core/url')->getCurrentUrl().'" target="_blank">' . $this->getLayout()->getBlock('head')->getTitle() . '</a>'; ?>
						<input type="hidden" name="current_url" id="callbacks_current_url" value="<?php echo htmlspecialchars($currentPageInfo); ?>">

						<div class="buttons-set">
							<input type="text" name="ajax" id="ajax" value="true" class="no-display" />
							<button type="submit" class="button button2" id="webform_2_submit_button" title="">
								<span>
									<span><?php echo $this->__("Send"); ?></span>
								</span>
							</button>
						</div>
					</form>
					<div class="loading-ajax-form" id="webform_2-ajax"></div>
					<script type="text/javascript">
						//<![CDATA[
						Event.observe(document, 'dom:loaded', function(){
							customerCallbacks.callbackInit();
							customerCallbacks.submitForm();
						});
						//]]>
					</script>
				</div>
			</div>
		</div>
		<i class="top"></i>
		<i class="bottom"></i>
	</div>
</div>
<script type="text/javascript">
	//<![CDATA[
	Validation.add('validate-phone-no-empty','<?php echo $this->__('You failed to enter phone.')?>',function(the_field_value){
		if(the_field_value == '+380 ')
		{
			return false;
		}
		return true;
	});
	//]]>
</script>