<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-print<?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
<div>
    <div class="print-head">
        <?php echo $this->getChildHtml('header.logo'); ?>
        <?php echo $this->getChildHtml('order.print.header.phones'); ?>
    </div>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
