<?php
/**
 * Brander_UnitopBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Brander
 * @package        Brander_UnitopBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 * @author         Alexandr Belyaev @AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php $data = $this->getCommentData();?>
<div class="form-add">
    <h2><?php echo $this->__('Write Your Comment') ?></h2>
    <?php if ($this->getAllowWriteCommentFlag()): ?>
        <form action="<?php echo $this->getAction() ?>" method="post" id="comment-form">
            <fieldset>
                <ul class="form-list">
                    <li>
                        <label for="name_field" class="required"><em>*</em><?php echo $this->__('Your Name') ?></label>
                        <div class="input-box">
                            <input type="text" name="name" id="name_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getName()) ?>" />
                        </div>
                    </li>
                    <?php if ($this->checkNecessarilyEmail()): ?>
                        <li>
                            <label for="email_field" class="required"><em>*</em><?php echo $this->__('E-mail') ?></label>
                            <div class="input-box">
                                <input type="text" name="email" id="email_field" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($data->getEmail()) ?>" />
                            </div>
                        </li>
                    <?php endif; ?>
                        <input type="hidden" name="title" id="title_field" class="input-text" value="<?php echo $this->escapeHtml($this->getPostTitle()) ?>" />
                    <li>
                        <label for="comment_field" class="required"><em>*</em><?php echo $this->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment_field" cols="5" rows="3" class="required-entry"><?php echo $this->escapeHtml($data->getComment()) ?></textarea>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Submit Comment') ?>" class="button"><span><?php echo $this->__('Submit Comment') ?></span></button>
            </div>
        </form>
        <script type="text/javascript">var commentForm = new VarienForm('comment-form');</script>
    <?php else: ?>
    <p class="review-nologged" id="comment-form">
        <?php echo $this->__('Only registered users can write comments. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
