<?php
/**
 * Up-sell products slider
 */
?>
<?php
$_collectionSize = count($this->getItemCollection()->getItems());
?>
<?php if ($_collectionSize): ?>
	<?php
	$theme = $this->helper('ultimo');
	$helpImg = $this->helper('infortis/image');
	$helpLabels = $this->helper('brander_shop/labels');
	$helpTemplate = $this->helper('ultimo/template');
	$sliderClasses = '';
	$gridClasses = '';

	$sliderId = "itemslider-upsell";

	//Slider parameters
	//--------------------------------------------------------------

	//Responsive mode on/off
	$isResponsive = true;

	//Assign number of items in a row to specific viewport width
	$breakpoints = $theme->getCfg('product_page/upsell_breakpoints');
	if (empty($breakpoints)) //Param not set
	{
		$breakpoints = '[0, 1], [320, 2], [480, 3], [960, 4], [1280, 5]'; //Set default breakpoints
	}

	//Pagination on/off
	$pagination = false;

	//Default image size
	$imgWidth = 295;
	$imgHeight = 295;

	//Image aspect ratio
	if ($theme->getCfg('category/aspect_ratio')) {
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio
	}

	//Slider timeout. Set to enable automatic scrolling.
	$timeout = intval($theme->getCfg('product_page/upsell_timeout'));

	//Number of items that should move on scrolling
	$move = 0;

	//If set, slider will loop
	$loop = $theme->getCfg('product_slider/loop');

	//Speed (arrows / touch swipe)
	$speed = intval($theme->getCfg('product_slider/speed'));

	//Speed (automatic scrolling / pagination)
	$autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

	//Pause slider on mouse hover
	$pause = $theme->getCfg('product_slider/pause');

	//Lazy loading
	$lazy = $theme->getCfg('product_slider/lazy');

	//Slider classes
	//--------------------------------------------------------------
	if ($isResponsive) {
		$sliderClasses .= ' itemslider-responsive';
	}

	if ($_collectionSize == 1) {
		$sliderClasses .= ' single-item';
	}

	//Product grid classes
	//--------------------------------------------------------------

	//Align elements to the center
	if ($theme->getCfg('category_grid/centered')) {
		$gridClasses .= ' centered';
	}
	?>
	<div class="block block-upsell">
		<h3 class="section-title padding-right"><?php echo $this->__('You may also be interested in the following product(s)'); ?></h3>

		<div
			class="itemslider-wrapper itemslider-upsell-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
			<div id="<?php echo $sliderId; ?>"
				 class="itemslider <?php if ($sliderClasses) echo $sliderClasses; ?> products-grid<?php if ($gridClasses) echo $gridClasses; ?>">
				<?php $this->resetItemsIterator() ?>
				<?php foreach ($this->getItemCollection()->getItems() as $_product): //$_link replaced with $_product ?>
					<div class="item">
						<div class="item-inner">
							<a href="<?php echo $_product->getProductUrl() ?>"
							   title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">

								<?php if ($lazy): ?>
									<img class="lazyOwl" src="#"
										 data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>"
										 alt="<?php echo $this->escapeHtml($_product->getName()) ?>"/>
								<?php else: ?>
									<img
										src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>"
										alt="<?php echo $this->escapeHtml($_product->getName()) ?>"/>
								<?php endif; ?>

								<?php if ($theme->getCfg('category/alt_image')): ?>
									<?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
								<?php endif; ?>

								<?php echo $helpLabels->getLabels($_product); //Product labels ?>
							</a>

							<?php //Add-to links
							if ($theme->getCfg('category_grid/display_addtolinks') != 0
								&& $theme->getCfg('category_grid/addtolinks_simple'))
							{
								if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
								{
									echo $helpTemplate->getCategoryAddtoWishLinks(
										$_product, 'addto-links-icons addto-onimage visible-onhover');

								}
								else //Always display
								{
									echo $helpTemplate->getCategoryAddtoWishLinks(
										$_product, 'addto-links-icons addto-onimage');
								}
							}
							?>

							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a>
							</div>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<div class="price-holder">
								<?php echo $this->getPriceHtml($_product, true, '-upsell') ?>
							</div>

							<div class="actions">
								<?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
									<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
								<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
									<a title="<?php echo $this->__('View Details') ?>" class="button btn-cart" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>

								<?php if (!$this->getHideButton()): ?>
									<?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
										<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
									<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
										<a title="<?php echo $this->__('View Details') ?>" class="button btn-cart" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
									<?php else: ?>
										<p class="availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"></p>
									<?php endif; ?>
								<?php endif; ?>

							</div>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
			<!-- end: itemslider -->
		</div>
		<!-- end: itemslider-wrapper -->
		<script type="text/javascript">
			//<![CDATA[
			jQuery(function ($) {

				var owl = $('#<?php echo $sliderId; ?>');
				owl.owlCarousel({

					<?php if ($lazy): ?>
					lazyLoad: true,
					<?php endif; ?>

					<?php if(!$isResponsive): ?>
					responsive: false,
					items: <?php echo $showItems; ?>,
					<?php else: ?>
					itemsCustom: [<?php echo $breakpoints; ?>],
					responsiveRefreshRate: 50,
					<?php endif; ?>

					<?php if ($speed): ?>
					slideSpeed: <?php echo $speed; ?>,
					<?php endif; ?>

					<?php if ($autoSpeed): ?>
					paginationSpeed: <?php echo $autoSpeed; ?>,
					<?php endif; ?>

					<?php if ($move !== 1): ?>
					scrollPerPage: true,
					<?php endif; ?>

					<?php if ($timeout): ?>
					autoPlay: <?php echo $timeout; ?>,
					<?php endif; ?>

					<?php if ($pause): ?>
					stopOnHover: true,
					<?php endif; ?>

					<?php if ($loop): ?>
					rewindNav: true,
					rewindSpeed: 600,
					<?php else: ?>
					rewindNav: false,
					<?php endif; ?>

					pagination: true,
					navigation: true,
					navigationText: false

				}); //end: owl

			});
			//]]>
		</script>

	</div> <!-- end: block -->
<?php endif; ?>
