<?php
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="s_ratings">
        <?php if ($this->getRatingSummary()):?>
            <span class="rating-box" style="overflow: auto;">
                <div class="rating" style="margin-right: 3px; width:<?php echo $this->getRatingSummary() ?>%"></div>
            </span>
        <?php endif;?>
    </div>
    <span style="float:left;"><a href="<?php echo $this->getReviewsUrl() ?>" class="a_review" onclick="var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl() ?>'; return false;"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a></span>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>