<div class="account-login home-login" id="login-tab">
    <h3 class="checkout-title"><?php echo $this->__('Login') ?></h3>
    <form class="login-form" action="<?php echo $this->getPostAction() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="note" style="display: none;"></div>
        <div class="field login-field-email">
            <label for="login:email">
                <?php echo $this->__('E-mail') ?>
            </label>
            <div class="input-box">
                <input type="text" class="input-text required-entry validate-email"
                       name="login[username]" id="login:email" />
            </div>
        </div>
        <div class="field login-field-pass">
            <label for="login:pass">
                <?php echo $this->__('Password') ?>
            </label>
            <div class="input-box">
                <input type="password" class="input-text required-entry validate-password"
                       name="login[password]" id="login:pass" />
            </div>
        </div>
        <div class="actions-set">
            <div class="buttons-set">
                <a href="<?php echo $this->helper('customer')->getForgotPasswordUrl(); ?>" class="open-lightbox forgot-pswd-link">
                    <span class="text"><?php echo $this->__('Forgot your password?') ?></span>
                </a>
                <button class="button btn-checkout">
                    <?php echo $this->__('Submit') ?>
                </button>
            </div>
        </div>
    </form>
    <?php echo $this->getChildHtml('social_auth'); ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    var loginForm = new VarienForm('login-form', false);
    //]]>
</script>