<div id="uni-wrapper-shipping-div" class="uni-wrapper-shipping" style="display:<?php echo 'none';?>">
    <form id="co-shipping-form" action="">
        <h4><?php echo $this->__('Shipping Address')?></h4>
		<?php if ($this->customerHasAddresses() && $this->getCustomer()->getPrimaryShippingAddress()) { ?>
			<?php
		    $shippingAddress = $this->getCustomer()->getPrimaryShippingAddress();
		    if($shippingAddress){
			    $shipData = $shippingAddress->getData();
			    if(is_array($shipData) && count($shipData)>0) {
			        $firstname = $shipData['firstname'];
			        $lastname = $shipData['lastname'];
			        $city = $shipData['city'];
			        $region = '';// $shipData['region'];
			        $postcode = $shipData['postcode'];
			        $country_id = $shipData['country_id'];
			        $telephone = '';// $shipData['telephone'];
			        $street1 = $shipData['street'];
			        //$street2 = $shipData['street'];
			        $region_id = $shipData['region_id'];
			    }
		    }
			?>
		<?php } else { ?>
		    <?php
                $firstname = $this->htmlEscape($this->getAddressShipping()->getFirstname());
			    $lastname = $this->htmlEscape($this->getAddressShipping()->getLastname());
			    $city = $this->htmlEscape($this->getAddressShipping()->getCity());
			    $region = $this->htmlEscape($this->getAddressShipping()->getRegion());
			    $postcode = $this->htmlEscape($this->getAddressShipping()->getPostcode());
			    $telephone = $this->htmlEscape($this->getAddressShipping()->getCity());
			    $street1 = $this->htmlEscape($this->getAddressShipping()->getStreet(1));
			    //$street2 = $this->htmlEscape($this->getAddressShipping()->getStreet(2));
			    $region_id = $this->getAddressShipping()->getRegionId();
			    $country_id = null;
			?>
		<?php } ?>

		<div id="shipping-imformation-fields">
            <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
            <input type="hidden" name="shipping[street][0]" id="shipping:street1" class="required-entry input-text com-box" value="<?php echo $street1; ?>"/>
            <input type="hidden" name="shipping[postcode]" id="shipping:postcode" value="<?php echo ($postcode) ? $postcode : '--- ---'; ?>"/>

            <label for="shipping:firstname"><?php echo $this->__('First Name') ?><span class="required">*</span></label>
            <input name="shipping[firstname]" type="text" id="shipping:firstname" class="required-entry input-text normal-box" value="<?php echo $firstname; ?>">
			<label for="shipping:lastname"><?php echo $this->__('Last Name') ?><span class="required">*</span></label>
			<input name="shipping[lastname]" type="text" id="shipping:lastname"  class="required-entry input-text normal-box" value="<?php echo $lastname; ?>"/>

            <?php if(Mage::helper('brander_opcheckout')->showCountries()) { ?>
                <label for="shipping:country_id"><?php echo $this->__('Country') ?><span class="required">*</span></label>
				<?php echo $this->getCountryHtmlSelectOPcheckout('shipping',$country_id) ?>
            <?php } else { ?>
                <input type="hidden" id="shipping:country_id" name="shipping[country_id]" value="<?php echo Mage::helper('brander_opcheckout')->getDefaultCountryId()?>"/>
            <?php } ?>

            <?php if(Mage::helper('brander_opcheckout')->showStates()) { ?>
                <label for="shipping:region"><?php echo $this->__('State') ?><span class="required">*</span></label></td>
            <?php } ?>

            <select <?php echo (!Mage::helper('brander_opcheckout')->showStates()) ? 'style="display:none"' : ''?> id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select com-box">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
                $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $region_id; ?>");
            </script>

            <?php if(Mage::helper('brander_opcheckout')->showStates()) { ?>
                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $region; ?>"  title="<?php echo $this->__('State/Province') ?>" style="display:none"  class="required-entry input-text com-box"/>
            <?php } else { ?>
                <input type="hidden" id="shipping:region" name="shipping[region]" value="<?php echo Mage::helper('brander_opcheckout')->getDefaultState()?>" class="required-entry input-text com-box"/>
            <?php } ?>

            <label for="shipping:telephone" class="masked-telephone"><?php echo $this->__('Telephone') ?><span class="required">*</span></label>
            <input name="shipping[telephone]" data-format="+380 dd ddd-dd-dd" type="text" id="shipping:telephone" class="required-entry input-text normal-box form-control bfh-phone validate-phone-no-empty" value="<?php echo $telephone; ?>"/>

            <label for="shipping:city"><?php echo $this->__('City') ?><span class="required">*</span></label>
            <input type="text" name="shipping[city]"  class="required-entry input-text normal-box" id="shipping:city" value="<?php echo $city; ?>" onblur="javascript: reloadShippingCity()"/>

            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
            <?php else:?>
                <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            <?php endif;?>
		</div>
	</form>
    <script type="text/javascript">
        var shippingForm = new VarienForm('co-shipping-form');
        shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
        var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions);
    </script>
</div>