<?php
/**
 * Brander_UnitopBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Brander
 * @package        Brander_UnitopBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 * @author         Alexandr Belyaev @AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php $_postscategories = $this->getPostscategories(); ?>
<?php if ($_postscategories->getSize() > 0) :?>
    <div class="page-title postscategory-title">
        <h2><?php echo $this->getCurrentPostscategory()->getTitle(); ?>:<?php echo $this->__('Children')?></h2>
    </div>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <div class="postscategory-list-container">
            <?php foreach ($_postscategories as $_postscategory) : ?>
                <div class="postscategory-list-item">
                    <a href="<?php echo $_postscategory->getPostscategoryUrl();?>" title="<?php echo $this->escapeHtml($_postscategory->getTitle()) ?>">
                        <?php echo $_postscategory->getTitle(); ?>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    <?php else : ?>
        <ul id="postscategories-list">
            <?php foreach ($_postscategories as $_postscategory) : ?>
                <?php echo $this->drawPostscategory($_postscategory);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            unitopblogTree('postscategories-list');
        </script>
    <?php endif;?>
<?php endif;?>
