<?php
/**
 * Brander_UnitopBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Brander
 * @package        Brander_UnitopBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 * @author         Alexandr Belyaev @AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php $_postscategories = $this->getPostscategories(); ?>
<div class="postscategory-title">
    <h3><?php echo Mage::helper('brander_unitopblog')->__('Categories') ?></h3>
</div>
<?php if ($_postscategories->getSize() > 0) :?>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <?php echo $this->getPagerHtml(); ?>
        <div class="postscategory-list-container">

            <?php if ($this->getActiveCategoryId()): ?>
                <div class="postscategory-list-item">
                    <a href="<?php echo Mage::helper('brander_unitopblog/postscategory')->getPostscategoriesUrl()?>">
                        <?php echo Mage::helper('brander_unitopblog')->__('Show All Posts');?>
                    </a>
                </div>
            <?php endif; ?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <ul id="postscategories-list">
            <?php foreach ($_postscategories as $_postscategory) : ?>
                <?php echo $this->drawPostscategory($_postscategory);?>
            <?php endforeach;?>

            <?php if ($this->getActiveCategoryId()): ?>
                <li>
                    <a href="<?php echo Mage::helper('brander_unitopblog/postscategory')->getPostscategoriesUrl()?>">
                        <?php echo Mage::helper('brander_unitopblog')->__('Show All Posts');?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
        <script type="text/javascript">
            unitopblogTree('postscategories-list');
        </script>
    <?php endif;?>
<?php else : ?>
    <?php echo Mage::helper('brander_unitopblog')->__('There are no post categories at this moment');?>
<?php endif;?>
