<div id="fastbuy_form" class="popup" style="display: none">
    <div class="popup-heading">
        <h2><?php echo $this->__("Buy One Click"); ?></h2>
        <a href="#" class="popup-btn">
            <span class="first-line"></span>
            <span class="last-line"></span>
        </a>
    </div>
    <?php $product = Mage::registry('current_product'); ?>
    <div class="popup-content">
        <form action="<?php echo $this->getUrl('preorder/index/post'); ?>" method="post" name="webform_3" id="webform_3" class="webforms-fastbuy" target="webform_3_iframe">
            <input type="hidden" name="product_id_preorder" id="product_id_preorder" value="<?php echo $product->getId(); ?>" style="display: none"/>

            <div class="row">
                <input type="text" name="name" id="field[11]" class="input-text required-entry" value="" placeholder="<?php echo $this->__("User Name"); ?>">
            </div>
            <div class="row">
                <input type="text" name="phone" id="field[12]" class="input-text required-entry mask-number" value="" placeholder="<?php echo $this->__("Phone"); ?>">
                <script type="text/javascript">
                    jQuery(".input-text.required-entry.mask-number").mask("+38 (999) 999-99-99");
                </script>
            </div>
            <div class="row">
                <input type="text" name="qty" id="product_qty_preorder" class="input-text required-entry" value="" placeholder="<?php echo $this->__("Qty"); ?>"
                       onkeyup="//<![CDATA[
                            this.value=this.value.replace(/[^\d]/,'');
                            //]]>"
                       onkeydown="//<![CDATA[
                          return ( event.ctrlKey || event.altKey
                    || (47<event.keyCode && event.keyCode<58 && event.shiftKey==false)
                    || (95<event.keyCode && event.keyCode<106)
                    || (event.keyCode==8) || (event.keyCode==9)
                    || (event.keyCode>34 && event.keyCode<40)
                    || (event.keyCode==46) );
                    //]]>"
                    >
            </div>
            <div class="row">
                <input type="textarea" name="comment" id="field[13]" class="input-text" value="" placeholder="<?php echo $this->__("Comment"); ?>">
            </div>
            <div class="btn-holder">
                <button type="submit" class="button btn-cart" id="webform_3_submit_button" title="submit">
                <span>
                    <span><?php echo $this->__("Buy"); ?></span>
                </span>
                </button>
            </div>
        </form>
    </div>
    <div class="loading-ajax-form" id="webform_3-ajax"></div>
    <script type="text/javascript">
        //<![CDATA[
        Event.observe(document, 'dom:loaded', function () {
            var fastbuyForm = new AjaxForm('webform_3', true);

            jQuery(".fancybox").fancybox({
                afterLoad : function() {
                    this.tpl.closeBtn = '<a title="<?php echo $this->__("Close");?>" class="fancybox-item fancybox-close" href="javascript:;"></a>'
                } // afterLoad
            }); // fancybox
        });


        //]]>
    </script>
</div>