<?php
/**
 * Brander_ProductBanners extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Brander
 * @package        Brander_ProductBanners
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Banner list template on product page
 *
 * @category    Brander
 * @package     Brander_ProductBanners
 * @author      AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php $banners = $this->getBannerCollection();?>
<?php if ($banners && $banners->count() > 0) :?>
<div class="box-collateral box-banners box-up-sell">
    <?php foreach ($banners as $_banner) : ?>
        <?php //echo $this->getChild('banner_view')->setCurrentBanner($_banner)->toHtml(); ?>
        <div class="item">
            <a href="<?php echo $_banner->getRedirectUrl()?>">
                <img class="product-banner" src="<?php echo Mage::helper('brander_productbanners/banner_image')->getImageBaseUrl() . $_banner->getImage()?>" />
            </a><br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
