<?php
/**
 * Brander_UnitopBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Brander
 * @package        Brander_UnitopBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 * @author         Alexandr Belyaev @AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php $_posts = $this->getPosts(); ?>
<?php if ($_posts->getSize() > 0) :?>
<div class="post-title">
    <h2><?php echo Mage::helper('brander_unitopblog')->__('Posts') ?></h2>
</div>
<div class="posts-list-container">
    <?php foreach ($_posts as $_post) : ?>
        <div class="post-list-item">
            <a href="<?php echo $_post->getPostUrl()?>">
                <?php echo $_post->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
