<?php
/**
 * Brander_UnitopBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Brander
 * @package        Brander_UnitopBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 * @author         Alexandr Belyaev @AlexVegas (alexvegas.brander@gmail.com)
 */
?>
<?php
$_products = $this->getProductCollection();
?>

<?php if($_products && $_products->getSize()): ?>
<?php
    $post = Mage::registry('current_post');
    $_products->addPriceData();
    $theme = $this->helper('ultimo');
    $helper = Mage::helper('brander_shop');
    $helpLabels = $this->helper('brander_shop/labels');
    $helpImg = $this->helper('infortis/image');

    $configuration = $helper->getCfg('brander_unitopblog/post_product_slider');

    if (!$configuration->getEnable()) {
        $configuration = $helper->getCfg('unitop_settings/products_sliders');
    }

    $sliderClasses = '';
    $gridClasses = '';

    $sliderId = "products-slider-post-".$post->getEntityId();

    //Slider parameters
    //--------------------------------------------------------------

    //Responsive mode on/off
    $isResponsive = $configuration->getIsResponsive(); //param: is_responsive
    if ($isResponsive === NULL) //Param not set
    {
        $isResponsive = true; //IMPORTANT: enabled by default
    }

    //Assign number of items in a row to specific viewport width
    $breakpoints = $configuration->getBreakpoints(); //param: breakpoints
    if ($breakpoints === NULL) //Param not set
    {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 5], [1280, 6]'; //Set default breakpoints
    }

    //Number of items in a row displayed if responsive mode is off
    $showItems = $configuration->getShowItems(); //param: show_items
    if (!$showItems) //Param not set or equals zero
    {
        $showItems = 5; //Set default number of items
    }

    //Pagination on/off
    $pagination = $configuration->getPagination(); //param: pagination

    //Slider initial delay
    $initDelay = 0;
    $initDelay = intval($configuration->getInitDelay()); //param: init_delay

    //Image width
    $imgWidth = $configuration->getImgWidth(); //param: img_width
    if ($imgWidth === NULL) //Param not set
    {
        $imgWidth = 196; //Set default value
    }
    else
    {
        $imgWidth = intval($imgWidth);
    }

    //Image aspect ratio
    if ($configuration->getAspectRatio())
    {
        $imgHeight = 0; //Keep aspect ratio - height will be calculated automatically based on width
    }
    else
    {
        $imgHeight = $imgWidth; //Don't keep aspect ratio - height is the same as width
    }

    //Image height
    if ($this->getImgHeight() !== NULL) //param: img_height
    {
        //If param is set, it overrides default height and aspect ratio settings
        $imgHeight = intval($this->getImgHeight());
    }

    //Slider timeout. Set to enable automatic scrolling.
    $timeout = $configuration->getTimeout(); //param: timeout
    if ($timeout === NULL) //Param not set
    {
        $timeout = intval($configuration->getCfg('product_slider/timeout'));
    }
    else
    {
        $timeout = intval($timeout);
    }

    //Number of items that should move on scrolling
    $move = $configuration->getMove(); //param: move
    if ($move === NULL) //Param not set
    {
        $move = 0; //By default scroll all visible items
    }
    else
    {
        $move = intval($move);
    }

    //If set, slider will loop
    $loop = $configuration->getLoop(); //param: loop
    if ($loop === NULL) //Param not set
    {
        $loop = 1;
    }

    //Speed (arrows / touch swipe)
    $speed = intval($configuration->getSpeed());

    //Speed (automatic scrolling / pagination)
    $autoSpeed = intval($configuration->getAutoSpeed());

    //Pause slider on mouse hover
    $pause = $configuration->getPause();

    //Lazy loading
    $lazy = $configuration->getLazy();

    //Slider classes
    //--------------------------------------------------------------
    if($isResponsive)
    {
        $sliderClasses .= ' itemslider-responsive';
    }

    if ($_products->getSize() == 1)
    {
        $sliderClasses .= ' single-item';
    }

    //Product grid classes
    //--------------------------------------------------------------
    //Size of grid elements
    $size = $configuration->getSize(); //param: size
    if ($size)
    {
        $gridClasses = ' ' . $size;
    }
    else
    {
        if ($showItems >= 8)
        {
            $gridClasses = ' size-xs';
        }
        elseif ($showItems >= 6)
        {
            $gridClasses = ' size-s';
        }
    }


    //Align elements to the center
    if ($configuration->getCentered())
    {
        $gridClasses .= ' centered';
    }

    //Set equal height for all items
    if ($configuration->getEqualHeight()) //param: equal_height
    {
        $gridClasses .= ' equal-height';
    }
?>

    <div class="block block-viewed">
        <h3 class="section-title padding-right"><?php echo $this->__('Attached Products'); ?></h3>
        <div class="itemslider-wrapper itemslider-viewed-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
            <div id="<?php echo $sliderId; ?>" class="itemslider <?php if($sliderClasses) echo $sliderClasses; ?> products-grid<?php if($gridClasses) echo $gridClasses; ?>">

                <?php foreach($_products as $_product): //$_link replaced with $_product ?>
                    <?php $_product->load('media_gallery'); ?>

                    <div class="item">
                        <div class="item-inner">
                            <div class="product-image-wrapper">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">

                                    <?php if ($lazy): ?>
                                        <?php $label = $this->escapeHtml($_product->getName()) ?>
                                        <img class="lazyOwl" src="#" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo ($label ? $label : 'product_image'); ?>" />
                                    <?php else: ?>
                                        <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                                    <?php endif; ?>
                                    <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                                </a>
                            </div>
                            <div class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a>
                            </div>
                            <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <div class="price-holder">
                                <?php echo $this->getPriceHtml($_product, true, '-post') ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div> <!-- end: itemslider -->
        </div> <!-- end: itemslider-wrapper -->

        <script type="text/javascript">
            //<![CDATA[
            jQuery(function($) {

                var owl = $('#<?php echo $sliderId; ?>');
                owl.owlCarousel({

                    <?php if ($lazy): ?>
                    lazyLoad: true,
                    <?php endif; ?>

                    <?php if(!$isResponsive): ?>
                    responsive: false,
                    items: <?php echo $showItems; ?>,
                    <?php else: ?>
                    itemsCustom: [ <?php echo $breakpoints; ?> ],
                    responsiveRefreshRate: 50,
                    <?php endif; ?>

                    <?php if ($speed): ?>
                    slideSpeed: <?php echo $speed; ?>,
                    <?php endif; ?>

                    <?php if ($autoSpeed): ?>
                    paginationSpeed: <?php echo $autoSpeed; ?>,
                    <?php endif; ?>

                    <?php if ($move !== 1): ?>
                    scrollPerPage: true,
                    <?php endif; ?>

                    <?php if ($timeout): ?>
                    autoPlay: <?php echo $timeout; ?>,
                    <?php endif; ?>

                    <?php if ($pause): ?>
                    stopOnHover: true,
                    <?php endif; ?>

                    <?php if ($loop): ?>
                    rewindNav: true,
                    rewindSpeed: 600,
                    <?php else: ?>
                    rewindNav: false,
                    <?php endif; ?>

                    <?php if ($pagination): ?>
                    pagination: true,
                    <?php else: ?>
                    pagination: false,
                    <?php endif; ?>

                    navigation: true,
                    navigationText: false,

                    afterInit: function() {
                        $('.item .product-name').dotdotdot();
                    }
                }); //end: owl
            });
            //]]>
        </script>

    </div>
<?php endif; ?>